<?php


namespace app\admin\controller;


use think\Controller;
use think\Db;

class Category extends Controller
{
//    只要访问类中的方法就会先调用这个方法
    public function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
//        权限验证，写在这里，代表这个类中的所有的方法都需要验证
        checkToken();
    }

//    分类添加
    public function add()
    {
//        1.验证权限？

        if (!$this->request->isPost()) {
            return json([
                "code" => 404,
                "msg" => "请求方式错误"
            ]);
        }
        $data = $this->request->post();
        $validate = validate("Category");
        $flag = $validate->check($data);
        if (!$flag) {
            return json([
                "code" => 404,
                "msg" => $validate->getError()
            ]);
        }
        $result = Db::table("category")->insert($data);
        if ($result) {
            return json([
                "code" => 200,
                "msg" => "分类添加成功"
            ]);
        } else {
            return json([
                "code" => 404,
                "msg" => "分类添加失败"
            ]);
        }
    }
//    分类查询
//查看数据、分页、搜索
//查看符合指定条件的某一页的若干条数据
//当前页数据返回时，返回数据总数
//limit(条数) page(页码)
    public function index()
    {
        if (!$this->request->isGet()) {
            return json([
                "code" => 404,
                "msg" => "请求方式错误"
            ]);
        }
        $data = $this->request->get();
//        isset用来判断变量是否有值，但是空字符串也会返回真
//        empty用来判断变量是否为空
        if (isset($data["page"]) && !empty($data["page"])) {
            $page = $data["page"];
        } else {
            $page = 1;
        }
        if (isset($data["limit"]) && !empty($data["limit"])) {
            $limit = $data["limit"];
        } else {
            $limit = 5;
        }
        $where = [];
        if (isset($data["cname"]) && !empty($data["cname"])) {
            $where["cname"] = ["like", "%" . $data["cname"] . "%"];
        }

        $category = Db::table("category")->field("cid,cname,cdesc")->where($where)->page($page)->limit($limit)->select();
        $count = Db::table("category")->where($where)->count();
        if ($category && $count) {
            return json([
                "code" => 200,
                "msg" => "数据获取成功",
                "data" => $category,
                "total" => $count
            ]);
        } else {
            return json([
                "code" => 200,
                "msg" => "暂无数据"
            ]);
        }
    }
}